
--Adding new a table 
DROP TABLE education_sql

CREATE TABLE education_sql (
	"YEAR" INT NOT NULL,
	"STATE" VARCHAR(250) NOT NULL,
	"NAME" VARCHAR(250) NOT NULL, 
	"AVG_SCORE" FLOAT NOT NULL,
	"TEST_SUBJECT" VARCHAR(225) NOT NULL, 
	"TEST_YEAR" INT NOT NULL, 
	"TOTAL_REVENUE" FLOAT NOT NULL,
	"FEDERAL_REVENUE" FLOAT,
	"STATE_REVENUE" FLOAT,
	"LOCAL_REVENUE" FLOAT,
	"TOTAL_EXPENDITURES" FLOAT NOT NULL, 
	"INSTRUCTION_EXPENDITURE" FLOAT,
	"SUPPORT_SERVICES_EXPENDITURE" FLOAT,
	"OTHER_EXPENDITURE" FLOAT);
	


SELECT * FROM education_sql


-- practice
SELECT DISTINCT ("STATE"), "AVG_SCORE"
FROM education_sql
GROUP BY "STATE", "AVG_SCORE"
ORDER BY "AVG_SCORE" DESC;

--

-- 




