
--Adding new a table 
DROP TABLE education_sql

CREATE TABLE education_sql (
	"YEAR" INT NOT NULL,
	"STATE" VARCHAR(250) NOT NULL,
	"NAME" VARCHAR(250) NOT NULL, 
	"AVG_SCORE" FLOAT NOT NULL,
	"TEST_SUBJECT" VARCHAR(225) NOT NULL, 
	"TEST_YEAR" INT NOT NULL, 
	"TOTAL_REVENUE" FLOAT NOT NULL,
	"FEDERAL_REVENUE" FLOAT,
	"STATE REVENUE" FLOAT,
	"LOCAL REVENUE" FLOAT,
	"TOTAL EXPENDITURES" FLOAT NOT NULL, 
	"INSTRUCTION_EXPENDITURE" FLOAT,
	"SUPPORT_SERVICES_EXPENDITURE" FLOAT,
	"OTHER_EXPENDITURE" FLOAT);
	
	

SELECT * FROM education_sql